In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
% pip install numpy

UsageError: Line magic function `%` not found.


In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
array_bidi_ = np.empty((4,2))
array_bidi_

array([[0.0000e+000, 0.0000e+000],
       [0.0000e+000, 0.0000e+000],
       [0.0000e+000, 1.1897e-320],
       [0.0000e+000, 0.0000e+000]])

# Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [7]:
array_randint_bi= np.random.randint(34, 98, (4,3))
array_randint_bi

array([[82, 75, 50],
       [60, 80, 92],
       [40, 51, 67],
       [90, 38, 69]])

# Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

# Las listas para crear los arrays son las siguientes

In [ ]:
# listas
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [9]:
lista1 = [34,56,71,98, 10]
array_unidi=np.array (lista1)
array_unidi

array([34, 56, 71, 98, 10])

In [10]:
lista2 = [[23,45,89, 56], [12,43,82,44]]
array_bidi=np.array (lista2)
array_bidi

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

# Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

# El primer elemento.

# Lo elementos que están en posición impar.

# Los cuatro primeros elementos.

# Los últimos tres elementos.

# Los elementos entre el 4 y el 8 (incluido).

In [14]:
array_unidi= np.arange (51)
array_unidi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
array_unidi [0] # primer elemento

0

In [ ]:
array_unidi [1::2] # elementos en posiciones impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
array_unidi [:4] # primeros 4 elementos

array([0, 1, 2, 3])

In [ ]:
array_unidi [-3:] # últimos 3 elementos

array([48, 49, 50])

In [ ]:
array_unidi [4:9] # elementos de la posición 4 a la 8

array([4, 5, 6, 7, 8])

# Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

# La primera fila y todas las columnas.

# Todas las filas pares.

# La primera columna y todas las filas.